### ISSUE TITLE
How to specify arguments?

### ISSUE THREAD

**Issue by bodhwani** [petrvacha/Character-recognition-by-neural-network#1]
python NN.py [??]
python NN.py digit is giving error

**Comment by petrvacha** [comment]
**python NN.py set mi**

set ... "hand" or "digit"
mi ... float number

Example:
```
python NN.py hand 0.8
python NN.py digit 0.4
```

For more information look at this [lines](https://github.com/petrvacha/Character-recognition-by-neural-network/blob/master/NN.py#L22).
